### ISSUE TITLE
Mimetypes: ROM files (consoles)

### ISSUE THREAD

**Issue by hlechner** [hlechner/hl-tests-repo#2]
![image](https://cloud.githubusercontent.com/assets/11244067/11255722/e15cd70a-8e2e-11e5-9c16-b702a9266b31.png)
Nintendo:
- [ ] **[NES](https://en.wikipedia.org/wiki/Nintendo_Entertainment_System) ROM** (application/x-nes-rom)
- [ ] **[Nintendo DS](https://en.wikipedia.org/wiki/Nintendo_DS) ROM** (application/x-nintendo-ds-rom) 
- [ ] **[Nintendo64](https://en.wikipedia.org/wiki/Nintendo_64) ROM** (application/x-n64-rom) 
- [ ] **[Game Boy](https://en.wikipedia.org/wiki/Game_Boy) ROM** (application/x-gameboy-rom) 
- [ ] **[Game Boy Advance](https://en.wikipedia.org/wiki/Game_Boy_Advance) ROM** (application/x-gba-rom)

Sega:
- [ ] **Sega [Master System](https://en.wikipedia.org/wiki/Master_System)/[Game Gear](https://en.wikipedia.org/wiki/Sega_Game_Gear) ROM** (application/x-sms-rom)
- [ ] **[Genesis](https://en.wikipedia.org/wiki/Sega_Genesis) ROM** (application/x-genesis-rom)

---

**Description:** 

> A **ROM image**, or **ROM file**, is a computer file which contains a copy of the data from a read-only memory chip, often from a video game cartridge, a computer's firmware, or from an arcade game's main board. The term is frequently used in the context of emulation, whereby older games or computer firmware are copied to ROM files on modern computers and can, using a piece of software known as an emulator, be run on a computer.

The idea behind it is to create icons for distinguish the ROM consoles files from other files.

**gvfs-info:** [here](https://github.com/hlechner/hl-tests-repo/blob/master/icons/consoles_rom_mimetypes.txt)

**Old Issue:** [879](https://github.com/numixproject/numix-icon-theme/issues/879)

**Design Association:** Console, Gamepad, Nintendo, Sega

**Note:** an idea by @Foggalong is to use a generic gaming symbol just changing the background color for each console.
## 
#### Icons as reference:

Numix-Circle Related Icons:
[ ![image](https://cloud.githubusercontent.com/assets/11244067/11405243/b2f6e40a-938d-11e5-8439-87590493be69.png)](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/nestopia.svg)[ ![image](https://cloud.githubusercontent.com/assets/11244067/11405273/dbf7c4c8-938d-11e5-9f25-245dad5ba58a.png)](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/vbam.svg)[ ![image](https://cloud.githubusercontent.com/assets/11244067/11405289/00f65e1a-938e-11e5-8c7a-131ce32105db.png)](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/gba.svg)[ ![image](https://cloud.githubusercontent.com/assets/11244067/11405329/292c2b4e-938e-11e5-84d3-e44661f20bbb.png)](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/gensgs.svg)
![image](https://cloud.githubusercontent.com/assets/11244067/11455518/9e9ca128-964b-11e5-959b-1412d4968351.png)![image](https://cloud.githubusercontent.com/assets/11244067/11455520/a6918bdc-964b-11e5-9413-ef1b1c46db80.png)![image](https://cloud.githubusercontent.com/assets/11244067/11455521/afbdb172-964b-11e5-9c8e-b4c7757d5c14.png)![image](https://cloud.githubusercontent.com/assets/11244067/11455523/b6e75016-964b-11e5-8f32-578ff912accf.png)![image](https://cloud.githubusercontent.com/assets/11244067/11455525/bd092230-964b-11e5-9142-cf869d8d7f98.png)![image](https://cloud.githubusercontent.com/assets/11244067/11455526/c5ef962c-964b-11e5-8419-15971c58d41d.png)![image](https://cloud.githubusercontent.com/assets/11244067/11455527/cd6ca64c-964b-11e5-9c94-fe5e80bbe8e8.png)
Numix Related Icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11455553/ad13fbce-964c-11e5-9046-d729a61f7e65.png)![image](https://cloud.githubusercontent.com/assets/11244067/11455555/b3ed8820-964c-11e5-84e6-1628debf7c73.png)
Non-Numix theme related icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11455576/b7141b62-964d-11e5-81d3-6e5e932c238e.png)![image](https://cloud.githubusercontent.com/assets/11244067/11455595/87e5056c-964e-11e5-9757-bd2f254c3d6b.png)
Other Individual icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11404954/f7a938fc-938b-11e5-922d-942a2153505c.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11404977/18d03fb2-938c-11e5-8bac-b2de300e80f4.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11404998/4ae1da06-938c-11e5-862b-9fd2bc99b764.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11405017/68242ec0-938c-11e5-95b0-2eebc4e8414c.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11405046/8a3f5f2a-938c-11e5-8cb8-b457972327ae.png)![image](https://cloud.githubusercontent.com/assets/11244067/11457937/bb113984-969d-11e5-8697-49aadf9c1ad0.png)![image](https://cloud.githubusercontent.com/assets/11244067/11457978/a7013d6c-969e-11e5-8c72-f5e6d49767db.png)
![image](https://cloud.githubusercontent.com/assets/11244067/11457934/a8a2bdc2-969d-11e5-9c75-814184598def.png)![image](https://cloud.githubusercontent.com/assets/11244067/11457940/e2cff636-969d-11e5-8d47-dfd31cf85732.png)![image](https://cloud.githubusercontent.com/assets/11244067/11457944/f5d55974-969d-11e5-97b4-8a3dfd420b63.png)![image](https://cloud.githubusercontent.com/assets/11244067/11457952/070a4fd8-969e-11e5-94cc-9a3f2fc8f946.png)![image](https://cloud.githubusercontent.com/assets/11244067/11458013/728ce9a4-969f-11e5-8003-bf1dafbcd51d.png)![image](https://cloud.githubusercontent.com/assets/11244067/11458015/7a180b68-969f-11e5-8c22-94d43e570a42.png)![image](https://cloud.githubusercontent.com/assets/11244067/11458177/45c270b2-96a2-11e5-8846-81af93fd44d8.png)

**Comment by hlechner** [comment]
First drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11458551/5ffeb8c6-96a9-11e5-9ad9-aeb4358490fa.png)![image](https://cloud.githubusercontent.com/assets/11244067/11460665/ece062a2-96d7-11e5-96eb-3066f1f71220.png)![image](https://cloud.githubusercontent.com/assets/11244067/11460666/00c7eefc-96d8-11e5-94f7-917ee8f27d03.png)![image](https://cloud.githubusercontent.com/assets/11244067/11460682/148e5034-96d8-11e5-9637-a9be44046a46.png)![image](https://cloud.githubusercontent.com/assets/11244067/11460752/e8e2bbbc-96d9-11e5-8377-7674bd217caa.png)

**Description:** This draft **does not** represent the final icon. It was developed just to check if the idea of colors in one generic control fit well. due to numbers of console and maybe very close colors I though that the two colors could fit better. What you think Foggalong?

**Comment by hlechner** [comment]
Second drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11609932/ef22385e-9b7a-11e5-949f-a1a2b97109b0.png)![image](https://cloud.githubusercontent.com/assets/11244067/11609933/f25ec4ce-9b7a-11e5-85b3-f2e0a9457f13.png)![image](https://cloud.githubusercontent.com/assets/11244067/11610081/596acc68-9b7f-11e5-9716-33208f418c7d.png)

**Description:** In this idea I use just the color from the Company's console (Nintendo and Sega), all consoles from the same company can share the same color, or using a default color for all consoles.

**Comment by andia89** [comment]
Yeah that's it. Is the text then necessary? (probably yes)

**Comment by hlechner** [comment]
Being totally honest I don't think its really necessary, I think it could be just cool could differentiate consoles ROM files.

Here the last icon without the text:
![image](https://cloud.githubusercontent.com/assets/11244067/11613669/3dfce8b2-9c10-11e5-9e52-3c90bf0faea5.png)

**Comment by bilelmoussaoui** [comment]
I think that having the text is better for larger sizes ;) (
