### ISSUE TITLE
Mimetypes: Virtualbox files

### ISSUE THREAD

**Issue by hlechner** [hlechner/hl-tests-repo#3]
![image](https://cloud.githubusercontent.com/assets/11244067/11069283/82ed724c-87bc-11e5-9ac8-b846b3b00f9b.png)
General:
- [ ] **VirtualBox Machine Definition** (virtualbox/vbox)
- [ ] **VirtualBox Extension Pack** (virtualbox/vbox-extpack)
- [ ] **[Open Virtual Appliance](https://en.wikipedia.org/wiki/Open_Virtualization_Format)** (virtualbox/ova)
- [ ] **[Open Virtualization Format](https://en.wikipedia.org/wiki/Open_Virtualization_Format)** (virtualbox/ovf)

Disk Files:
- [ ] **[Virtual Disk Image](https://en.wikipedia.org/wiki/VirtualBox#VirtualBox_Disk_Image)** (virtualbox/vdi)
- [ ] **[Virtual Hard Disk](https://en.wikipedia.org/wiki/VHD_%28file_format%29)** (virtualbox/vhd)
- [ ] **[Virtual Machine Disk](https://en.wikipedia.org/wiki/VMDK)** (virtualbox/vmdk)
- [ ] **Virtual Hard Disk** (virtualbox/hdd)

---

**Description:** The **Virtual Box** is a virtual machine software by Oracle. These mimetypes are added by the software itself into hicolor theme.

**Old Issue:** [859](https://github.com/numixproject/numix-icon-theme/issues/859)

**Design Association:** virtualbox logo, virtualization, Boxes, Hard Disks
## 
#### Icons as reference:

Numix-Circle Related Icons:
[ ![image](https://cloud.githubusercontent.com/assets/11244067/11410955/d0a3767e-93b2-11e5-8052-aa07f71007d9.png)](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/Vbox.svg?short_path=3032527)![image](https://cloud.githubusercontent.com/assets/11244067/11459089/8974c4a0-96b5-11e5-8c31-1eb9a4a29d04.png)![image](https://cloud.githubusercontent.com/assets/11244067/11459090/90f3322a-96b5-11e5-9d94-891209c26333.png)![image](https://cloud.githubusercontent.com/assets/11244067/11459093/9d07a6a4-96b5-11e5-9110-751aa6efcc32.png)![image](https://cloud.githubusercontent.com/assets/11244067/11459095/a47db5e0-96b5-11e5-9e3c-90a8add3ffd9.png)![image](https://cloud.githubusercontent.com/assets/11244067/11459328/40fd2aae-96bb-11e5-9d0d-a3c3c4b7a842.png)![image](https://cloud.githubusercontent.com/assets/11244067/11459330/481a7026-96bb-11e5-8af7-600c7ba3edc8.png)![image](https://cloud.githubusercontent.com/assets/11244067/11459334/4daa80e4-96bb-11e5-8fc7-7824e0ab381d.png)
Numix Related Icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11459150/109e6a8e-96b7-11e5-8547-7be248b4000b.png)
Other Individual icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11459108/286f472e-96b6-11e5-8d08-29e2b8bf31dd.png)![image](https://cloud.githubusercontent.com/assets/11244067/11459180/b8b9aaa8-96b7-11e5-973a-69531b52c7e6.png)![image](https://cloud.githubusercontent.com/assets/11244067/11459189/f0a9b12e-96b7-11e5-8721-5170cc01d5d2.png)

**Comment by hlechner** [comment]
#### Disk:

First Drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11459438/b3952826-96bd-11e5-9206-d058ed73be1b.png)
**Description:** The problem with this kind of design is the smaller icons. I need to think of another solution.

**Comment by andia89** [comment]
What if you keep the white line (the one that looks like a heartbeat line) from the first icon and remove everything else?

**Comment by hlechner** [comment]
#### Disk:

![image](https://cloud.githubusercontent.com/assets/11244067/11460201/c201d488-96cf-11e5-8695-d30c983e654f.png)![image](https://cloud.githubusercontent.com/assets/11244067/11460205/cf3ac6f0-96cf-11e5-8e2b-72bc5ceb7845.png)![image](https://cloud.githubusercontent.com/assets/11244067/11460206/e4a527f6-96cf-11e5-8e0c-4598130dc474.png)
**Description:** Nice idea, a lot better, maybe I change the colors to differentiate the type of files. But how about the 16px? I had to simplify the logo to fit in, however I'm not sure about the result.

**Comment by andia89** [comment]
I like it a lot, nice idea with simplyfying the 16px icon

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11608697/2019ad5c-9b58-11e5-8291-0145b1360a80.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608698/242247d8-9b58-11e5-8162-03a80dec3806.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608700/29716bc4-9b58-11e5-9164-76c3db8d4c14.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608702/2fdb8652-9b58-11e5-9e13-1ff6042a49d2.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608704/38b99f02-9b58-11e5-92f7-fdd135b3aff0.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608706/3ddf5ba2-9b58-11e5-9f1c-bd6f53478012.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608708/4464a5ae-9b58-11e5-8475-74b30f7fe46f.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608709/4b730e94-9b58-11e5-83fb-ef3798069d32.png)
![image](https://cloud.githubusercontent.com/assets/11244067/11608713/74673b40-9b58-11e5-8722-9c80d7907c54.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608715/7a55feba-9b58-11e5-85cf-adf4b5cea220.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608718/814dd260-9b58-11e5-995d-604ec1a30881.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608719/8617a2ee-9b58-11e5-8112-8bf01626c88e.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608720/8ad906ec-9b58-11e5-8a07-dcc2891bf0fe.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608722/8fda46c4-9b58-11e5-880e-35c4b500a3a1.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608911/80816378-9b5e-11e5-92f3-6a4bfd557ecd.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608723/95d35908-9b58-11e5-9de6-42baf1e75f16.png)
(32 not finished yet)
![image](https://cloud.githubusercontent.com/assets/11244067/11608814/85aacf86-9b5b-11e5-96b7-e3576c04dac5.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608816/8960e372-9b5b-11e5-964e-e544d08b3585.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608817/8ed47684-9b5b-11e5-88aa-1a968d4516df.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608818/901f3e70-9b5b-11e5-8a4f-ad1501907151.png)
![image](https://cloud.githubusercontent.com/assets/11244067/11608847/ac9dec94-9b5c-11e5-8465-0593ad76bbe1.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608850/b22a132c-9b5c-11e5-8c57-4bb73593eb05.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608851/b6acdefc-9b5c-11e5-9faa-28338464bf7b.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608852/bb352984-9b5c-11e5-9626-45367130dfa1.png)
![image](https://cloud.githubusercontent.com/assets/11244067/11608871/a7586fc4-9b5d-11e5-8938-0b85996f51b9.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608873/ab08c1fa-9b5d-11e5-81c3-2332e341636a.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608875/af287f0a-9b5d-11e5-80f8-dc60685745e0.png)![image](https://cloud.githubusercontent.com/assets/11244067/11608876/b39b328a-9b5d-11e5-95c4-21fcc93e57ee.png)

## 

Which font and size you guys use on 32px icons?

**Comment by andia89** [comment]
The font is Ubuntu Mono Bold

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11613623/d6e03d42-9c0e-11e5-8f46-8e2e71ae5f3a.png)
on 32px the text seems a little blurry, don't you think?

**Comment by bilelmoussaoui** [comment]
@hlechner You can remove the text for smaller sizes ;)

**Comment by hlechner** [comment]
thanks @bil-elmoussaoui, the 16,22 and 24 doesn't have any text just the 32,48,64 just to follow others mimetypes.

on 32px is kind "readable" but also blurry.

**Comment by Foggalong** [comment]
Yeah, text is blury on 32px but there isn't much we can do about it. We did a vote [about a year ago](https://plus.google.com/+NumixProjectOrg/posts/7khA9CMHyvD) and the overwhelming majority of people wanted to keep the text :(

**Comment by palob** [comment]
For the 32px text best alignment doesn't always result in optimal readability. It's a matter of tweaking letter positions and letter width or deforming letters itself.
You definitely can get the horizontal **H** line less blurry.

**Comment by hlechner** [comment]
good to know! I've tried basically use the ubuntu mono as 11 of height and then change to path and correct it manually.

I agree with the H, I'll correct, thanks for the tip!

**Comment by andia89** [comment]
we should make an alphabet for 32/48 and 64 with uppercase letters which can be used for these kind of icons...

**Comment by palob** [comment]
But you need to tweak the text for each icon individually. Especially W, M, K and X are a pain to get looking good.
