### ISSUE TITLE
Mimetypes: Lossless audio files

### ISSUE THREAD

**Issue by hlechner** [hlechner/hl-tests-repo#4]
![image](https://cloud.githubusercontent.com/assets/11244067/11429456/2cf0882a-945f-11e5-9e09-4aec1edbee45.png)
Lossless formats:
- [ ] [**FLAC audio**](https://en.wikipedia.org/wiki/FLAC) ((audio/flac) (audio/x-flac) (audio/x-flac+ogg))
- [ ] [**WAV audio**](https://en.wikipedia.org/wiki/WAV) (audio/x-wav)
- [ ] [**Monkey's audio**](https://en.wikipedia.org/wiki/Monkey%27s_Audio) ((audio/x-monkeys-audio) (audio/x-ape))
- [ ] [**WavPack audio**](http://fileformats.archiveteam.org/wiki/WavPack) (audio/x-wavpack)
- [ ] [**TrueAudio audio**](http://fileformats.archiveteam.org/wiki/True_Audio) (audio/x-tta)
- [ ] [**Shorten audio**](http://fileformats.archiveteam.org/wiki/Shorten) (application/x-shorten)

---

**Description:**

> Lossless compression is a class of data compression algorithms that allows the original data to be **perfectly** reconstructed from the compressed data. By contrast, lossy compression permits reconstruction only of an approximation of the original data, though this usually improves compression rates (and therefore reduces file sizes).

The idea is to create a differentiated mimetype for lossless audio files, making it easy to be organized.

**gvfs-info:** [here](https://github.com/hlechner/hl-tests-repo/blob/master/icons/lossless_mimetypes.txt)

**Old Issue:** [595](https://github.com/numixproject/numix-icon-theme/issues/595)

**Design Association:** Music note symbols, sound waves, sound wave bars, Premium sign (Plus, Ribbon, Medal, etc)
## 
#### Icons as reference:

Numix-Circle Related Icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11433070/a7dfd2c6-949f-11e5-8733-1f6ba3d9a98e.png)![image](https://cloud.githubusercontent.com/assets/11244067/11433049/79997c6e-949f-11e5-8473-a0bf0526da89.png)![image](https://cloud.githubusercontent.com/assets/11244067/11433060/8ed87d82-949f-11e5-8ee3-0d6a6b0f2071.png)![image](https://cloud.githubusercontent.com/assets/11244067/11433066/99fc2b1e-949f-11e5-8fdd-7c529f1bf21a.png)![image](https://cloud.githubusercontent.com/assets/11244067/11433088/bac88720-949f-11e5-9669-d2a6114f2002.png)![image](https://cloud.githubusercontent.com/assets/11244067/11433102/ca6effe2-949f-11e5-8152-ecf2677fe271.png)![image](https://cloud.githubusercontent.com/assets/11244067/11433108/ec864e64-949f-11e5-8cf4-c27b477faddb.png)![image](https://cloud.githubusercontent.com/assets/11244067/11433111/fd4e4328-949f-11e5-8bd2-73e0a8fd00f5.png)![image](https://cloud.githubusercontent.com/assets/11244067/11433120/1d401ee0-94a0-11e5-91a3-b850f36c487b.png)![image](https://cloud.githubusercontent.com/assets/11244067/11433122/271db1ac-94a0-11e5-9ae3-d648a9137b8c.png)![image](https://cloud.githubusercontent.com/assets/11244067/11433130/43d88d58-94a0-11e5-8ce7-bcf298fd8f65.png)
Numix Related Icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11432714/4239901e-949b-11e5-8e57-658913b108ae.png)
Non-Numix theme related icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11431308/86f15f6c-947c-11e5-8849-255fa02bdc4a.png)![image](https://cloud.githubusercontent.com/assets/11244067/11433223/67db5798-94a1-11e5-8f34-b1777e81464a.png)![image](https://cloud.githubusercontent.com/assets/11244067/11433254/c2f3f5cc-94a1-11e5-8cc3-4d1954aebc91.png)
Other Individual Icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11415308/8e30448a-93e8-11e5-88a6-9b4514645e0f.png)![image](https://cloud.githubusercontent.com/assets/11244067/11415420/a28b1760-93e9-11e5-882f-92ce03524182.png)![image](https://cloud.githubusercontent.com/assets/11244067/11415336/cf9ef344-93e8-11e5-96b6-6dd4bcb1c625.png)![image](https://cloud.githubusercontent.com/assets/11244067/11415373/2b679852-93e9-11e5-958f-570b899516f2.png)![image](https://cloud.githubusercontent.com/assets/11244067/11453454/58daabb6-95f2-11e5-9e14-590d9816c671.png)![image](https://cloud.githubusercontent.com/assets/11244067/11453461/7729fc3e-95f2-11e5-9206-68cc1efd697f.png)![image](https://cloud.githubusercontent.com/assets/11244067/11453481/136b16a0-95f3-11e5-9996-15ac975fff48.png)

**Comment by hlechner** [comment]
First Drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11455444/4205e090-9647-11e5-9ce3-bdddee95fefe.png)![image](https://cloud.githubusercontent.com/assets/11244067/11459794/ea684ad8-96c5-11e5-8896-737ddcd5b7c4.png)

**Description:** The result of this draft is not good enough, however I cound't think of nothing better at this moment.

**Comment by andia89** [comment]
I guess the design is not in line with all the other mimetypes. Maybe just a different colour? (not sure about this one, though)

**Comment by hlechner** [comment]
Yea, I totally agree, its definitively not numix style, actually I need a different design.

I just tried it because i'm totally stuck on this.

If you have any idea even if its not a polished idea please let me know.

**Comment by hlechner** [comment]
new drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11614635/a5b4a0b6-9c2f-11e5-9afb-1d068d875656.png)![image](https://cloud.githubusercontent.com/assets/11244067/11614636/ad2aa8ae-9c2f-11e5-9725-7581a1ff4232.png)![image](https://cloud.githubusercontent.com/assets/11244067/11614637/b4e91832-9c2f-11e5-9948-3049a3b1176e.png)![image](https://cloud.githubusercontent.com/assets/11244067/11614640/bb5b9cda-9c2f-11e5-88b9-2819e42a3ffe.png)

**Description:** Yea, I've no idea why I've used the orange color there. Even knowing that this doesn't fit on numix style I modifed this a bit just for test.

**Comment by andia89** [comment]
Nicer for sure. Still not sure how this symbolises lossless audio...

**Comment by hlechner** [comment]
"Still not sure how this symbolises lossless audio"
Same here :P

I've searched A LOT and I found nothing that remind me directly a lossless audio. Then I start trying with what I already have (nothing really good).

**Comment by hlechner** [comment]
Due to I couldn't make any progress on this i decide to close this issue and update the original one on Numix repo.
