### ISSUE TITLE
Mimetypes: Shared Library files

### ISSUE THREAD

**Issue by hlechner** [hlechner/hl-tests-repo#6]
![image](https://cloud.githubusercontent.com/assets/11244067/11402943/5a685546-9381-11e5-8a3b-239adc83cff9.png)
Shared library files:
- [x] **shared library** (application/x-sharedlib)
- [x] **libtool shared library** (application/x-shared-library-la)

---

**Description:** 

> A **shared library** or shared object is a file that is intended to be shared by executable files and further shared object files. Modules used by a program are loaded from individual shared objects into memory at load time or run time

Its comparable to **DLL** files of windows system.

**gvfs-info:** [here](https://github.com/hlechner/hl-tests-repo/blob/master/icons/sharedlib_mimetypes.txt)

**Old Issues:** [557](https://github.com/numixproject/numix-icon-theme/issues/557) [559](https://github.com/numixproject/numix-icon-theme/issues/559)

**Design Association:** Gears

**Note:** Its possible to use the same mimetype for both.
## 
#### Icons as reference:

Related to other OS icons: Windows (dll) and Mac OS X (dylib):
![image](https://cloud.githubusercontent.com/assets/11244067/10590695/df7a96b2-7690-11e5-962e-2ec006c9c7dd.png)![image](https://cloud.githubusercontent.com/assets/11244067/10590718/fcffecbe-7690-11e5-8b3f-4145d4b12baa.png)![image](https://cloud.githubusercontent.com/assets/11244067/11328420/8162e718-9171-11e5-8229-5925045a71fb.png)![image](https://cloud.githubusercontent.com/assets/11244067/11328443/ea36aafe-9171-11e5-9607-939dd9da6333.png)
Numix Related Icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11454765/d81cb4c2-9620-11e5-82ec-8974ea51f2c4.png)
Numix-Circle Related Icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11454746/28467f60-9620-11e5-9885-271fffa9e18b.png)
Non-Numix theme related icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11328497/a8d46d16-9172-11e5-9f08-fb070ca352a1.png)![image](https://cloud.githubusercontent.com/assets/11244067/11450134/c95db9c4-9579-11e5-9f35-81b5b56b3d33.png)
Other Individual icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11329955/2c4a0504-918a-11e5-9c0d-d80dd5a33693.png)![image](https://cloud.githubusercontent.com/assets/11244067/11329963/4a629ff6-918a-11e5-9034-ecb226302b3b.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11415151/5dbcefe4-93e6-11e5-93e7-fcae0a2a55a8.png)![image](https://cloud.githubusercontent.com/assets/11244067/11449832/e1691e44-956c-11e5-9ec6-a0d1bc40b3e4.png)![image](https://cloud.githubusercontent.com/assets/11244067/11449837/0e2f73d8-956d-11e5-874c-1e917be1abd3.png)![image](https://cloud.githubusercontent.com/assets/11244067/11449847/4eeebc58-956d-11e5-903f-0b6e237fb4dd.png)![image](https://cloud.githubusercontent.com/assets/11244067/11450002/b77c3692-9572-11e5-8cbb-666d50bc4db9.png)![image](https://cloud.githubusercontent.com/assets/11244067/11453478/ef538108-95f2-11e5-88a2-de3801dff873.png)

**Comment by hlechner** [comment]
First Drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11454905/df7ded0a-9628-11e5-8597-4d45c0b3d710.png)![image](https://cloud.githubusercontent.com/assets/11244067/11454922/1a7e9850-9629-11e5-92ec-64a08c9f9054.png)![image](https://cloud.githubusercontent.com/assets/11244067/11454925/399524f2-9629-11e5-8829-8c0692390b02.png)![image](https://cloud.githubusercontent.com/assets/11244067/11461383/64998718-96e9-11e5-9ce4-cf1eafbe976e.png)![image](https://cloud.githubusercontent.com/assets/11244067/11461385/6a3b6600-96e9-11e5-83f1-cb535aefda5d.png)

**Description:** This drafts are based on the Oxygen idea and the EvolvereSuit theme logo. The idea of books are discarded to not be confused with ebooks and gears to not be confused with .desktop files or with the makefiles.

**Comment by andia89** [comment]
last one is good imo

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11609543/d39d2d82-9b70-11e5-80cd-05479c6add0d.png)![image](https://cloud.githubusercontent.com/assets/11244067/11609546/db2b83aa-9b70-11e5-99e1-7189d671a45c.png)![image](https://cloud.githubusercontent.com/assets/11244067/11609548/ea5cf87c-9b70-11e5-9c58-1186950a40c0.png)

**Small Alternatives:**
24:
![image](https://cloud.githubusercontent.com/assets/11244067/11609611/78464dfe-9b72-11e5-9689-1d742ac625fa.png)![image](https://cloud.githubusercontent.com/assets/11244067/11609607/69e86170-9b72-11e5-95e5-87095c7f1e26.png)![image](https://cloud.githubusercontent.com/assets/11244067/11609609/729e752a-9b72-11e5-9564-61c6f1e333ba.png)
16:
![image](https://cloud.githubusercontent.com/assets/11244067/11609594/1d7936c0-9b72-11e5-8f16-3821b0ddf3fd.png)![image](https://cloud.githubusercontent.com/assets/11244067/11609595/2563389a-9b72-11e5-83f7-e93c14472608.png)![image](https://cloud.githubusercontent.com/assets/11244067/11609598/3184dee4-9b72-11e5-945c-5690a9fae1bf.png)

**Comment by andia89** [comment]
Top I sould use the first icon from 16 as smallll alternative (also for 22 and 24)

**Comment by hlechner** [comment]
mimetype merged.
