### ISSUE TITLE
Mimetypes: RAW image files

### ISSUE THREAD

**Issue by hlechner** [hlechner/hl-tests-repo#7]
![image](https://cloud.githubusercontent.com/assets/11244067/11389040/29b68502-9323-11e5-9b5d-697c08e30b9c.png)
- [ ] [**Adobe DNG negative**](http://fileformats.archiveteam.org/wiki/DNG) (image/x-adobe-dng)
- [ ] [**Canon CR2 raw image**](http://fileformats.archiveteam.org/wiki/Canon_RAW_2) (image/x-canon-cr2)
- [ ] [**Canon CRW raw image**](http://fileformats.archiveteam.org/wiki/Camera_Image_File_Format) (image/x-canon-crw)
- [ ] [**Fuji RAF raw image**](http://fileformats.archiveteam.org/wiki/Fujifilm_RAF) (image/x-fuji-raf)
- [ ] [**Kodak KDC raw image**](http://fileformats.archiveteam.org/wiki/Kodak) (image/x-kodak-kdc)
- [ ] [**Kodak DCR raw image**](http://fileformats.archiveteam.org/wiki/Kodak) (image/x-kodak-dcr)
- [ ] [**Minolta MRW raw image**](http://fileformats.archiveteam.org/wiki/Minolta_MRW) (image/x-minolta-mrw)
- [ ] [**Nikon NEF raw image**](http://fileformats.archiveteam.org/wiki/Nikon) (image/x-nikon-nef)
- [ ] [**Olympus ORF raw image**](http://fileformats.archiveteam.org/wiki/Olympus_ORF) (image/x-olympus-orf)
- [ ] [**Panasonic raw2 image**](http://fileformats.archiveteam.org/wiki/Panasonic_RAW/RW2) (image/x-panasonic-raw2)
- [ ] [**Panasonic raw image**](http://fileformats.archiveteam.org/wiki/Panasonic_RAW/RW2) (image/x-panasonic-raw)
- [ ] [**Pentax PEF raw image**](http://fileformats.archiveteam.org/wiki/Pentax_PEF) (image/x-pentax-pef)
- [ ] [**Sigma X3F raw image**](http://fileformats.archiveteam.org/wiki/X3F) (image/x-sigma-x3f)
- [ ] [**Sony ARW raw image**](http://fileformats.archiveteam.org/wiki/Sony_ARW) (image/x-sony-arw)

---

**Description:** 

> A camera **raw image file** contains minimally processed data from the image sensor of either a digital camera, image scanner, or motion picture film scanner. Raw files are named so because they **are not yet processed and therefore are not ready to be printed or edited with a bitmap graphics editor**. Normally, the image is processed by a raw converter in a wide-gamut internal colorspace where precise adjustments can be made before conversion to a "positive" file format such as TIFF or JPEG for storage, printing, or further manipulation, which often encodes the image in a device-dependent colorspace.

The idea is to create a specific mimetype icon for RAW image files. to be recognized from non-raw images files.

**gvfs-info:** [here](https://github.com/hlechner/hl-tests-repo/blob/master/icons/camera_RAW_mimetypes.txt)

**Design Association:** Camera Shutter, Lens, Camera, Photo

**Note:** can be used only one mimetype icon for all, or adding the file name for each mimetype.
## 
#### Icons as reference:

Numix-Circle Related Icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11428033/a5bc9ade-944e-11e5-91bf-b1947d7d91b2.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11428044/affc74c4-944e-11e5-94e2-3f83773e2698.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11428046/b551dea0-944e-11e5-948d-7348dd3ba0e0.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11428052/bad5d200-944e-11e5-8b46-336817277501.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11428057/bff43a42-944e-11e5-9648-86516940f7f6.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11428061/c54f900e-944e-11e5-8db3-d00c008f434b.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11428064/c9db3ace-944e-11e5-8e03-8628cde30ef5.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11428323/5d29575a-9451-11e5-91bc-020afa3fe22b.png)
Numix Related Icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11428101/16b10518-944f-11e5-97b5-2bc96f4d9997.png)
Non-Numix theme related icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11428293/06ed4bee-9451-11e5-9070-723b8c8827d2.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11428461/e911461e-9452-11e5-9eca-c42007fee318.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11430262/0e34c0f2-946b-11e5-994f-1d1eb9796226.png)![image](https://cloud.githubusercontent.com/assets/11244067/11430721/248354de-9472-11e5-9633-cf956aefd953.png)![image](https://cloud.githubusercontent.com/assets/11244067/11431223/57a9a0ae-947a-11e5-9538-a3fedc07cfeb.png)
Other Individual icons:
![image](https://cloud.githubusercontent.com/assets/11244067/11389238/7a1e13fa-9325-11e5-8246-770d5cb3e3b4.png)![image](https://cloud.githubusercontent.com/assets/11244067/11389248/93992b08-9325-11e5-98c9-209b0f2986b9.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11414972/76d2b494-93e3-11e5-80c2-530a28340fda.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11414996/d237bff0-93e3-11e5-8f76-54ed59591783.png)

**Comment by hlechner** [comment]
First Drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11455080/e3b69c2e-9631-11e5-881c-d3d8f529f9bf.png)![image](https://cloud.githubusercontent.com/assets/11244067/11455083/f1e3bee4-9631-11e5-9464-4c81e61a4df2.png)![image](https://cloud.githubusercontent.com/assets/11244067/11455084/f7193ad8-9631-11e5-9679-d5c4c8b4429d.png)

![image](https://cloud.githubusercontent.com/assets/11244067/11457702/d797ee92-9696-11e5-820f-25c89946cfa7.png)![image](https://cloud.githubusercontent.com/assets/11244067/11457707/e1633fa8-9696-11e5-9173-ba1213cb3955.png)![image](https://cloud.githubusercontent.com/assets/11244067/11457708/e999c782-9696-11e5-98e9-f3edbed05ca9.png)![image](https://cloud.githubusercontent.com/assets/11244067/11457710/f19828f2-9696-11e5-95ff-ea358d0cfe21.png)![image](https://cloud.githubusercontent.com/assets/11244067/11457711/fae04a0c-9696-11e5-81fb-55a506c67ba2.png)![image](https://cloud.githubusercontent.com/assets/11244067/11455080/e3b69c2e-9631-11e5-881c-d3d8f529f9bf.png)
**Description:** using the default image mimetype as base and use the hotshots.svg from Numix-Circle.

**Comment by andia89** [comment]
scales good :+1:
